### ISSUE TITLE
PointProcess

### ISSUE THREAD

**Issue by lxkain** [kylebgorman/textgrid#13]
Hi, older versions used to support PointProcess, which is needed to read files that contain events such as GCI marks. Was there a specific reason that lead to removal? And/or: Any chance of re-inclusion?

**Comment by kylebgorman** [comment]
I really don't remember, sorry to say. If I had to guess it may have been
removed at the point when Max and Morgan got involved? (They more or less
forked my mostly-private project and then encouraged me to upload the
result to GitHub.)

Aren't PointProcesses promoted to TextGrids just a series of PointTiers? I
was under the impression this should be able to read and write those so
long as they're stored in "long form".

Here's the earliest version of the library I can find online:

    https://sourceforge.net/p/p2tk/code/HEAD/tree/python/praat/textgrid.py

Pull requests always accepted. Or I'd be willing to take a stab if you want
to send an example in.

Also worth checking out whether Meg Mitchell's module (also called
textgrid.py, and part of NLTK) has what you want.

K
