### ISSUE TITLE
Rounding should be done after division

### ISSUE THREAD

**Issue by naktinis** [kylebgorman/textgrid#24]
I'm getting overlapping IntervalTier segments and trying to find the cause for this.

There is [a line](https://github.com/kylebgorman/textgrid/blob/master/textgrid/textgrid.py#L821) in `MLF.add` that rounds a float and the divides it by the samplerate:

    pmin = round(float(line[0]), round_digits) / samplerate

However, this seems to defy the purpose of rounding. Here's an example:

    >>> round(1234.56789, 3)
    1234.568
    >>> round(1234.56789, 3) / 10000
    0.12345679999999999

Maybe it's better to define by samplerate and round afterwards, like this:

    pmin = round(float(line[0]) / samplerate, round_digits)

If you agree about this, I'm happy to file a pull request.

**Comment by kylebgorman** [comment]
This has been a consistent problem and I've struggled understanding why it happens, so if this addresses it, I'd love a pull request!

**Comment by naktinis** [comment]
I should probably clarify that I was getting the interval overlap errors in version 1.4. This code has changed since (it used to use `Decimal` and now uses `float` with rounding). I think the problem might have gone away incidentally in some cases after that change, but this fix will at least correct some rounding to behave as expected. Will file a pull request soon.

**Comment by naktinis** [comment]
Might be somewhat related to this issue: https://github.com/prosodylab/Prosodylab-Aligner/issues/66

**Comment by kylebgorman** [comment]
closed by #34ac4ef
