### ISSUE TITLE
PYPI release?

### ISSUE THREAD

**Issue by christianbrodbeck** [kylebgorman/textgrid#32]
Would it be possible to make a `pypi` release? I keep having to install from `master` because of some issues with the current release, and things seem pretty stable on GitHub.

**Comment by kylebgorman** [comment]
Sure. In fact would you like to be added as a maintainer on PyPi yourself?

**Comment by christianbrodbeck** [comment]
Sure

**Comment by kylebgorman** [comment]
What's your PyPi username?

**Comment by christianbrodbeck** [comment]
[christianbrodbeck](https://pypi.org/user/christianbrodbeck/) :) Should I make a PR for version bump?

**Comment by kylebgorman** [comment]
If you'd like! Added you.

I can be more help in the future but this is a very busy week for me, so
I'll stick to reviewing...

**Comment by christianbrodbeck** [comment]
Pushed to PYPI, thanks @kylebgorman !
