### ISSUE TITLE
__min__ and __max__

### ISSUE THREAD

**Issue by scjs** [kylebgorman/textgrid#7]
The TextGrid, IntervalTier, and PointTier classes have `__min__` and `__max__` methods defined to return the minTime and maxTime attributes. These two methods aren't included as Python magic methods, so you have to call them by name:

    it = textgrid.IntervalTier()
    it.add(5.0, 6.0, 'a segment')

    it.__min__()

which returns the minTime, 0.0

If you call `min(it)`, the IntervalTier returns the first interval `Interval(5.0, 6.0, a segment)`, and `min()` with a TextGrid returns the first/top tier. Go ahead and close if this is all intended behavior. I just saw the double underscores and went for `min()` but then didn't get what I expected.

**Comment by kylebgorman** [comment]
Closing this as scjs@'s PR eliminates them altogether and I'm okay with that.
